### ISSUE TITLE
Filter mit Relationen per AJAX laden

### ISSUE THREAD

**Issue by xarem** [whatwedo/CrudBundle#1]
Alle automatischen Filter, welche eine Relation durchsuchen (z.B. Gruppen -> Personen oder umgekehrt) sollen per AJAX geladen werden. Bei grösseren Tabellen (> 10'000 Einträge) werden die Ladezeiten ansonsten unzumutbar oder wir laufen in Timeouts / Memory Limits

Gleiches in Ticket #2 für Formularfelder

![screenshot 2017-01-24 13 34 02](https://cloud.githubusercontent.com/assets/647483/22247430/1121bd42-e23a-11e6-8202-3bcccf8ca223.png)

**Comment by n3r0-ch** [comment]
@Tuxes3 Wie ist der aktuelle Stand

**Comment by Tuxes3** [comment]
@n3r0-ch Noch zu besprechen vor Schliessung des Tickets. 
* SearchBundle
* ManyToMany
* ..

**Comment by n3r0-ch** [comment]
* SearchListener similar to https://github.com/whatwedo/TableBundle/blob/feature/v0.2.0/EventListener/SearchEventListener.php
* Add Many-To-Many

**Comment by Tuxes3** [comment]
review ready
