### ISSUE TITLE
Fix background height of "crud blocks" 

### ISSUE THREAD

**Issue by desi-bach** [whatwedo/CrudBundle#101]
## Is
class `whatwedo_crud-blocks whatwedo_crud-blocks--show h-full bg-neutral-50 p-4 flex flex-wrap items-baseline` has a specific height. With more blocks on a page, the background doesn't adjust automatically. 
Maybe the issue is already solved with #95 

## Should

- The background adjusts responsively to the correct height 

## Acceptance Criteria 

- [ ] The background of crud blocks is adjusted to the content and doesn't have a fix height 

![Screenshot 2022-08-12 at 11 31 36 copy](https://user-images.githubusercontent.com/102159086/184327109-9d29d1f2-993d-425d-a391-7331d94b4cd7.png)

**Comment by marcwieland95** [comment]
This is fixed by refactoring the full basic layout template
