### ISSUE TITLE
Box Templates mit Twig Blöcken erweitern.

### ISSUE THREAD

**Issue by tuxes3** [whatwedo/CrudBundle#18]
Mit commit e161ea0 wurde es Möglich die box Templates zu überschreiben. Zurzeit gibt es erst einen Twig Block (show.html.twig - add_button):

Überall wo es Sinn gibt einen Block hinzufügen.

**Comment by xarem** [comment]
Zurückgestellt da allgemeines Frontend-Refactoring vorgesehen
