### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by s4mpl3d** [whatwedo/CrudBundle#19]
https://github.com/whatwedo/CrudBundle/blob/97694f28077a699f223f18e4056d1805285dd82a/Form/EntityAjaxType.php#L28

sollte das nicht 'namespace whatwedo\CrudBundle\Form;' sein?

**Comment by xarem** [comment]
@Tuxes3 Beide Form Type's, welche aktuell im Ordner CrudBundle/Form sind müssen in CrudBundle/Form/Type verschoben werden und der Namespace muss Form\Type sein
