### ISSUE TITLE
Form Type für preselect definitions

### ISSUE THREAD

**Issue by xarem** [whatwedo/CrudBundle#20]
Wenn per Query-Parameter Informationen zu einer Entity erwartet werden, wird normalerweise als Form Type `EntityHiddenType` verwendet. Dies funktioniert jedoch nicht, wenn es nicht sicher ist, ob eine mitgegeben wird. In diesem Fall muss ein `AjaxSelectFormType` genommen werden. 

Aktuell muss dies mit Konditionen programmiert werden. Mittels einer Kreuzung der beiden (`PreselectEntityFormType`) könnte eine einfachere Lösung umgesetzt werden.

**Comment by s4mpl3d** [comment]
Wäre für mehrere Projekte ein sehr grosses +
