### ISSUE TITLE
CSV Export auslagern

### ISSUE THREAD

**Issue by xarem** [whatwedo/CrudBundle#29]
- Alle Infos aus dem DefinitionBuilder nehmen
- Als Extension
- ähnlich wie FilterExtension: allow add / remove of content / columns

**Comment by tuxes3** [comment]
@rugbymauri works on this.

**Comment by tuxes3** [comment]
@rugbymauri do not forget export file name: https://github.com/whatwedo/CrudBundle/issues/82
