### ISSUE TITLE
unintuitive parameter for content callable

### ISSUE THREAD

**Issue by 71m024** [whatwedo/CrudBundle#39]
https://github.com/whatwedo/CrudBundle/blob/ef8aefc94cf25f39a9f02b0c8b5007a7c6034e36/Content/AbstractContent.php#L149

Is it necessary to wrap the `$row` parameter into an array?

**Comment by lukasluecke** [comment]
Probably not. The only reason I could think of is the mention about passing by value / by reference in https://www.php.net/manual/de/function.call-user-func.php - but for that you'd have to create the array with the row as a reference.

Could you try it without the array, and see how that changes things?
