### ISSUE TITLE
remove DefinitionView::linkIt() use Formatter instead

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/CrudBundle#42]
instead of using the LinkIt() method to link the Entity use a "EntityLinkFormatter" instead

**Comment by rugbymauri** [comment]
@xarem @lukasluecke @s4mpl3d what do you think about it?

**Comment by lukasluecke** [comment]
@rugbymauri See comments on commit. Generally a good idea 👍

**Comment by lukasluecke** [comment]
@rugbymauri Could you create a PR for this, so we can finish the review there?
