### ISSUE TITLE
Update documentation for routing

### ISSUE THREAD

**Issue by s4mpl3d** [whatwedo/CrudBundle#48]
If you overwrite the default Crud-controller to add an Action, the definition on the Parent-controller is null.

To overcome this you have to set `,defaults={ "_resource"=XXXDefinition::class }` inside the Route annotation; eg
```
@Route("/feature/xxx", name="whatwedo_feature_xxx",defaults={ "_resource"=XXXDefinition::class })
```

This should be updated in the documentation.

**Comment by tuxes3** [comment]
🎉
