### ISSUE TITLE
Optimize sidebar

### ISSUE THREAD

**Issue by desi-bach** [whatwedo/CrudBundle#69]
## Is
When sidebar contains many entries, the sidebar offers not enough space

## Should
- Settings should be in a collapsible menu 
- Settings are collapsed as a default
- Font size must be 30% smaller and use less padding

## Acceptance Criteria

- [ ]  Settings are in a collapsible menu 
- [ ]  Settings are collapsed as a default
- [ ]  Font size and icons are 30% smaller (around 14px)
- [ ]  Padding top and bottom are 0.25rem

![Screenshot 2022-03-23 at 10 39 06](https://user-images.githubusercontent.com/102159086/159669240-c86b6123-3946-43a8-be2c-eb18223ed717.png)

**Comment by marcwieland95** [comment]
I tried to reduce the spacing. But it looks really ugly.

I think as a default we shouldn't do that. We can add submenus to clean the interface. If this still don't help we can override it on a per-project basis.

Without spacing:
<img width="376" alt="CleanShot 2022-09-02 at 15 10 52@2x" src="https://user-images.githubusercontent.com/6168975/188153626-36cfba41-d699-4fed-97f2-ba6a927a5986.png">

I left the padding of the main menus, but reduced it on the submenus:
<img width="391" alt="CleanShot 2022-09-02 at 15 08 37@2x" src="https://user-images.githubusercontent.com/6168975/188153722-39dbce40-99cd-447a-bdd5-3a3af254f6ae.png">
